spring:
   h2:
      console:
         enabled: true
   application:
      name: VoyageWebService
eureka:
   client:
      serviceUrl:
         defaultZone: http://Registry:8761/eureka/
   healthcheck:
      enabled: true
server:
  port : 8083